server:
  port: 9999
  session:
    lifetime:
      seconds: 900

spring:
  datasource:
    url: jdbc:postgresql://database:5432/sso
    username: sso
    password: Admin!23
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
        default_schema: public
        jdbc:
          batch_size: 150
        order_inserts: true
        order_updates: true
    open-in-view: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-root.xml

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone:
        http://172.31.0.1:8070/eureka/