server:
  port: 9999
  session:
  lifetime:
  seconds: 900

spring:
  datasource:
    url: jdbc:postgresql://database:5432/sso
    username: sso
    password: Admin!23
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
        default_schema: public
        jdbc:
          batch_size: 150
        order_inserts: true
        order_updates: true
    open-in-view: true